// Seed data — mirrors the INITIAL_JOBS in the frontend
const SEED_JOBS = [
  { title: 'Cashier - City Center Book Shop', company: 'City Center Book Store', location: 'Colombo 07', rate: 'LKR 1,500/hr', amount: 30000, type: 'Part-Time', tags: ['Retail', 'Customer Service', 'Cash Handling'], logoColor: 'bg-blue-500', description: 'Handle customer transactions at our busy bookshop in City Center. Manage point-of-sale systems, process payments accurately, and provide excellent customer service. Flexible hours perfect for campus students. No experience necessary - full training provided. Benefits include employee discount on books and magazines.', postedBy: 'company1' },
  { title: 'Cashier & Retail Associate - Food City Supermarket', company: 'Food City Supermarket', location: 'Colombo 03', rate: 'LKR 1,200/hr', amount: 24000, type: 'Part-Time', tags: ['Retail', 'Cashier', 'Supermarket'], logoColor: 'bg-green-600', description: 'Work as a cashier and retail assistant at Food City. Responsibilities include operating checkout systems, scanning items, handling payments, and assisting customers with their shopping. Evening and weekend shifts available. Competitive pay with performance bonuses. Employee discounts on groceries and household items.', postedBy: 'company2' },
  { title: 'Leaflet Promotions - MultiCare Pharmaceuticals', company: 'MultiCare Pharmaceuticals', location: 'Colombo 04', rate: 'LKR 1,800/hr', amount: 36000, type: 'Part-Time', tags: ['Marketing', 'Promotions', 'Outreach'], logoColor: 'bg-red-500', description: 'Distribute promotional leaflets for MultiCare Pharmaceuticals across busy commercial areas in Colombo. Engage with potential customers, answer basic questions about health products, and collect feedback. Flexible 4-6 hour shifts. Weather protection and materials provided. Great way to earn while improving communication skills.', postedBy: 'company3' },
  { title: 'Brand Ambassador - Mobile Phone Distribution', company: 'Digital Tek Solutions', location: 'Colombo 09', rate: 'LKR 2,000/hr', amount: 40000, type: 'Part-Time', tags: ['Marketing', 'Promotions', 'Sales'], logoColor: 'bg-purple-600', description: 'Promote latest mobile phones and plans from Digital Tek Solutions at malls and commercial hubs. Demonstrate products, engage customers, and achieve daily targets. Commissions based on successful promotions. Flexible weekend schedules. No sales experience needed - comprehensive training provided.', postedBy: 'company4' },
  { title: 'Event Promoter - Fashion & Lifestyle', company: 'StyleZone Marketing', location: 'Kandy', rate: 'LKR 2,200/hr', amount: 44000, type: 'Part-Time', tags: ['Marketing', 'Events', 'Promotions'], logoColor: 'bg-pink-500', description: 'Promote fashion and lifestyle brands at shopping malls and commercial events. Hand out samples, explain product features, and engage with customers. Perfect for students interested in marketing. Event-based work with flexible scheduling. Free branded merchandise and performance bonuses.', postedBy: 'company5' },
  { title: 'Stock Counting & Inventory Helper - Colombo Warehouse', company: 'Global Logistics Sri Lanka', location: 'Colombo 14', rate: 'LKR 1,600/hr', amount: 32000, type: 'Part-Time', tags: ['Warehouse', 'Inventory', 'Organization'], logoColor: 'bg-orange-600', description: 'Assist with stock counting and inventory management at our Colombo warehouse. Responsibilities include counting items, organizing shelves, scanning barcodes, and maintaining records. Physical work in a climate-controlled environment. Flexible evening and weekend shifts. Great for students who prefer hands-on work.', postedBy: 'company6' },
  { title: 'Store Stock Assistant - Supermarket Chain', company: 'Smart Shopping Stores', location: 'Galle', rate: 'LKR 1,400/hr', amount: 28000, type: 'Part-Time', tags: ['Retail', 'Stock Management', 'Warehouse'], logoColor: 'bg-cyan-600', description: 'Help stock shelves and manage inventory at Smart Shopping stores. Unpack deliveries, organize products by category, maintain shelf appearance, and handle stock audits. Physical work in a clean, organized environment. Flexible scheduling around your campus timetable. Opportunities for advancement.', postedBy: 'company7' },
  { title: 'Vehicle Count & Inventory - Transport Company', company: 'Island Wide Transport Services', location: 'Colombo 02', rate: 'LKR 2,500/hr', amount: 50000, type: 'Part-Time', tags: ['Logistics', 'Inventory', 'Counting'], logoColor: 'bg-yellow-600', description: 'Count and track vehicles in our large fleet for Island Wide Transport Services. Record vehicle locations, maintenance status, and prepare inventory reports. Use company systems and software. Regular 4-hour shifts available. Work in a professional logistics environment. No prior experience necessary.', postedBy: 'company8' },
  { title: 'Hotel Housekeeping - 4-Star Hotel', company: 'Royal Palm Hotel Colombo', location: 'Colombo 03', rate: 'LKR 1,900/hr', amount: 38000, type: 'Part-Time', tags: ['Hospitality', 'Housekeeping', 'Hotel'], logoColor: 'bg-amber-600', description: 'Join our housekeeping team at Royal Palm Hotel Colombo. Responsibilities include cleaning guest rooms, maintaining common areas, changing linens, and ensuring high cleanliness standards. Professional uniform provided. Flexible shifts including mornings and afternoons. Excellent training and supportive team environment.', postedBy: 'company9' },
  { title: 'Hotel Restaurant Attendant - City Center', company: 'Grand Hotel & Restaurant', location: 'Colombo 07', rate: 'LKR 1,700/hr', amount: 34000, type: 'Part-Time', tags: ['Hospitality', 'Food Service', 'Customer Service'], logoColor: 'bg-red-600', description: 'Work as a restaurant attendant at Grand Hotel. Clear tables, serve customers, arrange place settings, and maintain dining area cleanliness. Professional attire provided. Training in customer service standards. Flexible evening and weekend shifts. Interact with diverse clientele and build hospitality experience.', postedBy: 'company10' },
  { title: 'Front Desk Reception - Boutique Hotel', company: 'Paradise Bay Hotel', location: 'Negombo', rate: 'LKR 2,100/hr', amount: 42000, type: 'Part-Time', tags: ['Hospitality', 'Reception', 'Customer Service'], logoColor: 'bg-blue-600', description: 'Welcome guests and manage front desk operations at Paradise Bay Hotel. Handle check-ins/check-outs, answer inquiries, maintain guest records, and provide exceptional service. English fluency required. Professional environment with career growth opportunities. Flexible scheduling for students.', postedBy: 'company11' },
  { title: 'Kitchen Helper & Food Prep - Restaurant', company: 'Taste of Colombo Restaurant', location: 'Colombo 05', rate: 'LKR 1,350/hr', amount: 27000, type: 'Part-Time', tags: ['Hospitality', 'Food Service', 'Kitchen'], logoColor: 'bg-orange-500', description: 'Assist kitchen staff with food preparation, washing dishes, and maintaining kitchen cleanliness. Learn basic cooking techniques and food safety standards. Supportive, fast-paced environment. Flexible shifts around your studies. Staff meals provided. Great stepping stone to culinary career.', postedBy: 'company12' },
  { title: 'Floral Arranger & Decorator - Event Company', company: 'Bloom Designs Event Decor', location: 'Colombo 06', rate: 'LKR 2,300/hr', amount: 46000, type: 'Part-Time', tags: ['Decoration', 'Events', 'Florals', 'Creative'], logoColor: 'bg-pink-600', description: 'Create beautiful floral arrangements and designs for weddings, corporate events, and celebrations. Learn floral design techniques while earning. Arrange flowers, prepare centerpieces, and deliver decorations to event venues. Creative work with flexible scheduling. Perfect for artistic students. No experience needed - full training provided.', postedBy: 'company13' },
  { title: 'Event Decorator - Balloons & Props', company: 'Party Perfect Celebrations', location: 'Kandy', rate: 'LKR 2,000/hr', amount: 40000, type: 'Part-Time', tags: ['Decoration', 'Events', 'Setup'], logoColor: 'bg-purple-500', description: 'Decorate event spaces for birthdays, weddings, and corporate functions. Set up balloons, hang decorations, arrange furniture, and create festive atmospheres. Physical work requiring attention to detail. Flexible event-based scheduling. Evening and weekend work. Fun, creative, and rewarding!', postedBy: 'company14' },
  { title: 'Wedding & Events Setup - Decoration Team', company: 'Elegant Events Sri Lanka', location: 'Colombo 04', rate: 'LKR 2,400/hr', amount: 48000, type: 'Part-Time', tags: ['Events', 'Decoration', 'Setup'], logoColor: 'bg-rose-600', description: 'Set up and decorate wedding venues, banquet halls, and event spaces for Elegant Events. Install tables, chairs, decorations, lighting, and floral arrangements. Work with professional event teams on various occasions. Physical work with flexible scheduling. Great for students who enjoy creative and dynamic environments.', postedBy: 'company15' },
  { title: 'Graphic Designer - Digital Branding', company: 'Creative Pixel Studios', location: 'Colombo', rate: 'LKR 3,500/hr', amount: 87500, type: 'Freelance', tags: ['Design', 'Branding'], logoColor: 'bg-orange-500', description: 'Create stunning visual designs for local and international marketing campaigns. Work with modern design tools and deliver high-quality branding assets for growing businesses.', postedBy: 'company1' },
  { title: 'UX/UI Designer - Mobile Apps', company: 'TechFlow Asia', location: 'Colombo, Western Province', rate: 'LKR 8,000/hr', amount: 200000, type: 'Full-Time', tags: ['UI/UX', 'Figma', 'Mobile'], logoColor: 'bg-blue-600', description: 'Design user-friendly interfaces for mobile applications targeting the Asian market. Collaborate with development teams to create seamless user experiences.', postedBy: 'company2' },
  { title: 'English Tutor for O/L & A/L Students', company: 'EduLearn Sri Lanka', location: 'Kandy', rate: 'LKR 2,000/hr', amount: 50000, type: 'Part-Time', tags: ['Teaching', 'English', 'Exam Prep'], logoColor: 'bg-green-500', description: 'Teach English language and literature to O/L and A/L students. Help students prepare for national exams with proven teaching methodologies.', postedBy: 'company1' },
  { title: 'Social Media Manager - Sinhala & English', company: 'Local Buzz Marketing', location: 'Galle', rate: 'LKR 3,000/hr', amount: 75000, type: 'Contract', tags: ['Marketing', 'Social Media', 'Content'], logoColor: 'bg-pink-500', description: 'Manage social media accounts for local SMEs and startups. Create engaging content in Sinhala and English, manage community engagement, and track analytics.', postedBy: 'company1' },
  { title: 'Data Entry Specialist', company: 'BPO Solutions Sri Lanka', location: 'Colombo 01', rate: 'LKR 2,800/hr', amount: 56000, type: 'Part-Time', tags: ['Data Entry', 'Administrative', 'Office'], logoColor: 'bg-indigo-600', description: 'Enter and manage data for our BPO operations. Accuracy and attention to detail required. Work in a professional office environment. Flexible shifts available including evenings. No experience necessary with basic typing skills.', postedBy: 'company16' },
  { title: 'Call Center Executive - English & Sinhala', company: 'Global Customer Support', location: 'Colombo 05', rate: 'LKR 2,500/hr', amount: 50000, type: 'Part-Time', tags: ['Customer Service', 'Call Center', 'Communication'], logoColor: 'bg-teal-600', description: 'Handle customer service calls for international clients. Fluency in English and Sinhala required. Professional training provided. Work in a team environment with modern communication tools. Flexible shifts with performance incentives.', postedBy: 'company17' },
  { title: 'Online Tutor - Mathematics & Science', company: 'Virtual Academy Sri Lanka', location: 'Remote', rate: 'LKR 2,200/hr', amount: 44000, type: 'Freelance', tags: ['Teaching', 'Online', 'Education'], logoColor: 'bg-lime-600', description: 'Teach mathematics and science to students online from anywhere. Create lessons, conduct one-on-one sessions, and track student progress. Flexible scheduling perfect for campus life. Work from home with flexible hours. Competitive compensation.', postedBy: 'company18' },
  { title: 'Content Writer - Sinhala & English', company: 'Digital Content Hub', location: 'Colombo 06', rate: 'LKR 3,000/hr', amount: 60000, type: 'Freelance', tags: ['Writing', 'Content', 'Marketing'], logoColor: 'bg-fuchsia-600', description: 'Write engaging content for blogs, websites, and social media in Sinhala and English. Create SEO-optimized articles, product descriptions, and marketing copy. Work from home with flexible deadlines. Perfect for students with writing skills.', postedBy: 'company19' },
  { title: 'Delivery Assistant - Food & Packages', company: 'Express Couriers Sri Lanka', location: 'Colombo 09', rate: 'LKR 1,800/hr', amount: 36000, type: 'Part-Time', tags: ['Delivery', 'Logistics', 'Transportation'], logoColor: 'bg-amber-500', description: 'Deliver food orders and courier packages in Colombo area. Use company vehicle or own transportation (with allowance). Meet customers, handle payments, and provide excellent service. Flexible scheduling with incentives for peak hours.', postedBy: 'company20' },
];

module.exports = SEED_JOBS;
